project:
  type: website

website:
  title: The Awesome Lab
  navbar:
    background: "#FFFFFF"
    search: false
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



