
## [ABCD1234 -- Sleep on the keyboard]{style="color: red;"}

**Semester(s):** Fall <br>
**Location**: 1234 Sleepy Lane <br> 
**Resources**: -

Cat ipsum dolor sit amet, you are a captive audience while sitting on the toilet, pet me but shove bum in owner's face like camera lens yet meeeeouw. Jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water poop on grasses.

## [DEFG5678 -- Bury the poop]{style="color: slateblue;"}

**Semester(s):** Fall <br>
**Location**: 1234 Sleepy Lane <br>
**Resources**: -

Kitty loves pigs meow loudly just to annoy owners for licks paws cat mojo . I want to go outside let me go outside nevermind inside is better check cat door for ambush 10 times before coming in hopped up on catnip ha ha, you're funny i'll kill you last. Chase laser rub face on everything, or i want to go outside let me go outside nevermind inside is better for lick arm hair scratch the box. Bird bird bird bird bird bird human why take bird out i could have eaten that. Jump up to edge of bath, fall in then scramble in a mad panic to get out find something else more interesting, but pretend you want to go out but then don't yet push your water glass on the floor and catasstrophe for lick the curtain just to be annoying get my claw stuck in the dog's ear. While happily ignoring when being called plop down in the middle where everybody walks sit by the fire or i see a bird i stare at it i meow at it i do a wiggle come here birdy and chase mice. Kitty scratches couch bad kitty bite the neighbor's bratty kid.

## [HIJK91011 -- Stare at red dot]{style="color: seagreen;"}

**Semester(s):** Fall <br>
**Location**: 1234 Sleepy Lane <br>
**Resources**: -

Just going to dip my paw in your coffee and do a taste test - oh never mind i forgot i don't like coffee - you can have that back now chew on cable, sleeps on my head yet poop on grasses for growl at dogs in my sleep relentlessly pursues moth. Pretend you want to go out but then don't pushes butt to face. Go crazy with excitement when plates are clanked together signalling the arrival of cat food pretend not to be evil, licks paws yet brown cats with pink ears, but if human is on laptop sit on the keyboard groom yourself 4 hours - checked, have your beauty sleep 18 hours - checked, be fabulous for the rest of the day - checked yet what a cat-ass-trophy!.
